### ISSUE TITLE
Blender-Launcherのインポート機能

### ISSUE THREAD

**Issue by Chipsnet** [Chipsnet/blender-hub#12]
あっちにはあっちの良さあるし、インポートできたら便利じゃね？

**Comment by Chipsnet** [comment]
なんかビルドすると
```
 [error] Error: Command failed: cscript.exe //Nologo C:\Users\Minato86\AppData\Local\Programs\blender-hub\resources\app.asar\node_modules\regedit\vbs\regList.wsf A HKCU\SOFTWARE\blender_launcher\settings

    at ChildProcess.exithandler (child_process.js:304:12)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

が出て動かない

ここらへんが参考にはなりそう
https://github.com/ironSource/node-regedit/issues/52
